# Generated by Django 5.1 on 2024-08-29 09:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DessertDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Unnamed Dessert', max_length=200)),
                ('flavors', models.TextField(default='No specific flavors')),
                ('rating', models.FloatField(default=0.0)),
                ('success', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Nom par défaut', max_length=200)),
                ('description', models.TextField(default='Description par défaut')),
                ('cuisine', models.CharField(default='Cuisine par défaut', max_length=100)),
                ('course', models.CharField(default='Course par défaut', max_length=100)),
                ('diet', models.CharField(default='Diet par défaut', max_length=100)),
                ('prep_time', models.CharField(default='Temps de préparation par défaut', max_length=50)),
                ('ingredients', models.TextField(default='Ingrédients par défaut')),
                ('instructions', models.TextField(default='Instructions par défaut')),
                ('image_url', models.URLField(default='http://example.com/default-image.jpg', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dessert_disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dessertdisponible')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('plat_disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.platdisponible')),
            ],
        ),
        migrations.CreateModel(
            name='MenuDuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('desserts', models.ManyToManyField(to='menu.dessertdisponible')),
                ('plats', models.ManyToManyField(to='menu.platdisponible')),
            ],
        ),
    ]
