# Generated by Django 5.1 on 2024-08-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessertdisponible',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='platdisponible',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='platdisponible',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platdisponible',
            name='cuisine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platdisponible',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platdisponible',
            name='diet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platdisponible',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='platdisponible',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platdisponible',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platdisponible',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='platdisponible',
            name='prep_time',
            field=models.CharField(max_length=50),
        ),
    ]
