# Generated by Django 5.1 on 2024-08-29 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adresse'),
        ('menu', '0002_dessertdisponible_prix_platdisponible_prix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.adresse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeDessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.commande')),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dessertdisponible')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='desserts',
            field=models.ManyToManyField(through='menu.CommandeDessert', to='menu.dessertdisponible'),
        ),
        migrations.CreateModel(
            name='CommandePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.platdisponible')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='plats',
            field=models.ManyToManyField(through='menu.CommandePlat', to='menu.platdisponible'),
        ),
    ]
